language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo clean
  - cargo test

matrix:
  allow_failures:
  - rust: nightly
  - rust: beta

before_install:
  - sudo apt-get update

install:
  - PATH=$PATH:/home/travis/.cargo/bin

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/v34.tar.gz &&
  tar xzf v34.tar.gz &&
  cd kcov-34 &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-34 &&
  find target/debug -maxdepth 1 -name 'cernan-*' -type f | while read file; do
    [ -x $file ] || continue;
    mkdir -p "target/cov/$(basename $file)";
    kcov --exclude-pattern=/.cargo,/usr/lib  --include-path="$(pwd)" --verify "target/cov/$(basename $file)" "$file";
  done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
