coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true
    changes: false

    patch:
      default:
        target: 90%

    project:
      default:
        target: 95%
        threshold: 1%

comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
