data-directory = "data-receiver/"

[statsd]
enabled = false

[graphite]
enabled = false

flush-interval = 10

[tags]
service = "receiver"
uhf_band = "s"
source = "cernan"

[federation_receiver]
port = 1972
ip = "0.0.0.0"

[wavefront]
port = 2878
host = "127.0.0.1"

[console]
