use metric::{MetricKind, Metric};
use std::str::FromStr;
use string_cache::Atom;

grammar;

MetricName: Atom = <s:r"[A-Za-z][_A-Z0-9a-z+/=\.@%-]*"> => Atom::from(s);

Num: f64 = <s:r"[-+]?[0-9]+\.?[0-9]*"> => f64::from_str(s).unwrap();

MetricLine: Metric = {
    <name:MetricName> <val:Num> <t:Num> => Metric::new_with_time(name, val, Some(t as i64), MetricKind::Raw, None)
};

pub MetricPayload: Vec<Metric> = { (<MetricLine>)+ };
