[template]
src = "cernan.toml.tmpl"
dest = "/etc/cernan.toml"
uid = 0
gid = 0
# In the case of the 'env' backend keys map to uppercase underscore-separated vars.
# ex. /statsd/port == STATSD_PORT
keys = [
    "/statsd/port",
]
